Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2024
Var
   x, y, soma : real


Inicio
   escreval("Digite um numero : ", x)
   leia(x)
   escreval("Digite um outro número : ", y)
   leia(y)
   
   soma <- x + y
   escreval("A soma dos algoritmos digitados é : ", soma)

Fimalgoritmo